"""Add Transactions Model

Revision ID: 903833af2b2b
Revises: db78efba6547
Create Date: 2024-05-02 15:10:12.422157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "903833af2b2b"
down_revision: Union[str, None] = "db78efba6547"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("sum", sa.Integer(), nullable=False),
        sa.Column(
            "type_pay",
            sa.Enum("Баланс", "Премиум", name="typepay", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "pay_method",
            sa.Enum(
                "Карты",
                "СБП | Скины | Крипта",
                "Админ",
                "CryptoBot",
                name="paymentmethod",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
